version: '3.8'

services:
  ghibli-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./database.json:/app/database.json
      - ./templates:/app/templates
      - ./static:/app/static
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - GUNICORN_CMD_ARGS="--log-level debug"
    restart: unless-stopped
    networks:
      - ghibli-network

networks:
  ghibli-network:
    driver: bridge 